### ISSUE TITLE
Добавить лого Я.музыки и Яндекса

### ISSUE THREAD

**Issue by mitrokun** [iswitch/ha-yandex-icons#12]
Рексвестирую, по возможности, добавить сопутствующие иконки.  А то в остальных паках им тоже места не нашлось. 
Референсное чб изображение для музыки можно взять тут:
https://yandex.ru/support/music/performers-and-copyright-holders/icon.html

Лого Яндекса, как вариант:
https://ru.m.wikipedia.org/wiki/Файл:Yandex_icon.svg
https://play-lh.googleusercontent.com/WFJgS6wkeaFCVFp3CH6mWOd2sRsWvOxILagnw33PFi4KFYnPsaeCGywSVwqJzwrHtJQ=w240-h480

**Comment by iswitch** [comment]
Добавил
