### ISSUE TITLE
Иконка пропадает если ее поставить во вкладку

### ISSUE THREAD

**Issue by tayanov** [iswitch/ha-yandex-icons#3]
Если иконку поставить во вкладку, то она пропадает через некоторое время и больше не появляется.

**Comment by ASGASG1** [comment]
тоже пропадает во вкладке

**Comment by BertTomsk** [comment]
Аналогичная проблема

**Comment by HepoH3** [comment]
А еще практически сразу пропадает с карточки picture-elements.

**Comment by iswitch** [comment]
Иконки делались по докам https://developers.home-assistant.io/blog/2020/05/09/custom-iconsets/
Видимо проблема в HA. У меня тоже пропадают во вкладке(
