### ISSUE TITLE
Другой путь к иконкам

### ISSUE THREAD

**Issue by and7ey** [iswitch/ha-yandex-icons#7]
У меня при установке через HACS оказался другим путь к иконкам- 

/local/community/ha-yandex-icons/yandex-icons.js

предлагаю указать на это в описании

**Comment by iswitch** [comment]
Можно использовать как /local/community, так и /hacsfiles.
https://hacs.xyz/docs/categories/plugins/#custom-view-hacsfiles

**Comment by and7ey** [comment]
С /hacsfiles у меня не заработало, а с /local/community - все ок.

**Comment by iswitch** [comment]
Добавил)
